// changing tags here currently requires changing tags on the client side too

export const tagOptions = [
  {title: 'Grooves', value: 'Grooves'},
  {title: 'Drum Fills', value: 'Drum Fills'},
  {title: 'TesseracT', value: 'TesseracT'},
  {title: 'Odd timing', value: 'Odd timing'},
  {title: 'Polyrhythms', value: 'Polyrhythms'},
  {title: 'Displacement', value: 'Displacement'},
  {title: 'Metric Modulation', value: 'Metric Modulation'},
  {title: 'Single kick', value: 'Single kick'},
  {title: 'Double Kick', value: 'Double Kick'},
  {title: 'Hand Technique', value: 'Hand Technique'},
  {title: 'Foot Technique', value: 'Foot Technique'},
  {title: 'Rudiments', value: 'Rudiments'},
  {title: 'Gear', value: 'Gear'},
  {title: 'Programming drums', value: 'Programming drums'},
  {title: 'Practice routine', value: 'Practice routine'},
  {title: 'Technique', value: 'Technique'},
  {title: 'Flow', value: 'Flow'},
  {title: 'Limb Independence', value: 'Limb Independence'},
  {title: 'Ghost Notes', value: 'Ghost Notes'},
  {title: 'Triplets', value: 'Triplets'},
  {title: 'Hertas', value: 'Hertas'},
  {title: 'Slow', value: 'Slow'},
  {title: 'Dynamics', value: 'Dynamics'},
  {title: 'Three', value: 'Three'},
  {title: 'Five', value: 'Five'},
  {title: 'Seven', value: 'Seven'},
  {title: 'Nine', value: 'Nine'},
]
