export const tagOptions = [
  {title: 'Drum fills', value: 'Drum fills'},
  {title: 'Grooves', value: 'Grooves'},
  {title: 'Rudiments', value: 'Rudiments'},
  {title: 'Polyrhythms', value: 'Polyrhythms'},
  {title: 'Odd Timing', value: 'Odd Timing'},
  {title: 'Double Kick', value: 'Double Kick'},
  {title: 'Single Kick', value: 'Single Kick'},
  {title: 'Basic techniques', value: 'Basic techniques'},
  {title: 'Flow', value: 'Flow'},
  {title: 'Limb Independence', value: 'Limb Independence'},
  {title: 'TesseracT', value: 'TesseracT'},
  {title: 'Single Strokes', value: 'Single Strokes'},
  {title: 'Double Strokes', value: 'Double Strokes'},
  {title: 'Ghost Notes', value: 'Ghost Notes'},
  {title: 'Paradiddle', value: 'Paradiddle'},
]
